---
- hosts: all
  become: true
  tasks:
  - name: certbot dependency repo
    apt_repository:
      repo: "deb http://deb.debian.org/debian stretch-backports main"
      state: present
  - name: install apt dependencies
    apt:
      name:
        - certbot
        - python-certbot-nginx
        - git
        - nginx
      default_release: stretch-backports
      state: latest
      update_cache: true
  - name: nginx service running
    service:
      name: nginx
      state: started
  - name: install website
    git:
      repo: 'https://github.com/bob-crutchley/PostcardProject'
      dest: /opt/PostcardProject
  - name: check for certificates
    stat:
      path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
    register: certificate
  - name: configure TLS
    shell: "certbot certonly --nginx -n --agree-tos --email test@gmail.com --domains '{{ inventory_hostname }}'"
    when: certificate.stat.exists == False
  - name: nginx config
    template:
      src: ../resources/nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Reload NGINX
    service:
      name: nginx
      state: reloaded
  
